export const supportedProjectsNames = [
  'Libft',
  'Get_Next_Line',
  'ft_ls',
  'FdF',
  'ft_printf',
  'minishell',
  'Wolf3d',
  'C Exam Alone In The Dark - Beginner',
  "Fract'ol",
  'Corewar',
  'RTv1',
  'RT',
  'Hotrace',
  'Filler',
  'Push_swap',
  'Lem_in',
  'ft_sh2',
  'ft_select',
  'ft_sh3',
  '42sh',
  'Malloc',
  'Nm-otool',
  'ft_script',
  'Philosophers',
  'ft_p',
  'IRC',
  'Lem-ipc',
  'Zappy',
  'Piscine PHP',
  'Piscine CPP',
  'mod1',
  'LibftASM',
  'Abstract VM',
  'Open Project I',
  'Root-me | App-Systeme',
  'Savoir Relier',
  'N-puzzle',
  'Expert System',
  'Gomoku',
  'ComputorV1',
  'First Internship',
  'Taskmaster',
  'Scop',
  '42run',
  'Part-time',
  'Final Internship',
  'Piscine OCaml',
  'Piscine Unity',
  'ft_hangouts',
  'Bomberman',
  'Electronics',
  'ft_linear_regression',
  'KrpSim',
  '21sh',
  'Rubik',
  'HumanGL',
  'Swifty Companion',
  'Camagru',
  'ft_minirogue',
  'ft_ping',
  'Fillit',
  'ft_traceroute',
  'ft_nmap',
  'Matcha',
  'Hypertube',
  'ft_turing',
  'Snow Crash',
  'Darkly',
  'Open Project II',
  'Swifty Proteins',
  'ft_ality',
  'In the Shadows',
  'Particle System',
  'init',
  'roger-skyline-2',
  'cloud-1',
  'ft_linux',
  'little-penguin-1',
  'RainFall',
  'Dr Quine',
  'Woody Woodpacker',
  'Matt Daemon',
  'Filesystem',
  'KFS-1',
  'KFS-2',
  'KFS-3',
  'Music Room',
  'Piscine Python Django',
  'Piscine Swift iOS',
  'Piscine Reloaded',
  'Piscine Ruby on Rails',
  '42 Commandements',
  'Red Tetris',
  'H42N42',
  'Famine',
  'KFS-4',
  'KFS-5',
  'ComputorV2',
  'docker-1',
  'KFS-6',
  'KFS-7',
  'KFS-8',
  'KFS-9',
  'KFS-X',
  'ft_db',
  'Pestilence',
  'War',
  'Death',
  'Boot2Root',
  'Durex',
  'Override',
  'KIFT',
  'ft_ssl_rsa',
  'ft_ssl_md5',
  'ft_ssl_des',
  'DSLR',
  'GUImp',
  'Piscine PHP Symfony',
  'Doom Nukem',
];
